### ISSUE TITLE
Linked content for reproducible science 

### ISSUE THREAD

**Issue by rachaelgallagher** [open-traits-network/open-traits-network.github.io#10]
We are building a set of resources and links to add to our website

**Comment by chiras** [comment]
We have a few reproducible tutorials for the FENNEC that could be used here: https://fennec.readthedocs.io/en/latest/user.html#case-studies

**Comment by hoganhaben** [comment]
a few links from the Slack workspace-- 

Open Science badges:  [](https://cos.io/our-services/open-science-badges/)'

COPDESS statement (Coalition for Publishing Data in the Earth and Space Sciences)
[](http://www.copdess.org/enabling-fair-data-project/commitment-to-enabling-fair-data-in-the-earth-space-and-environmental-sciences/)

**Comment by jhpoelen** [comment]
@hoganhaben probably needless to say but please note that FAIR (as in https://www.force11.org/group/fairgroup/fairprinciples) does not mandate open (as in https://opendefinition.org/). Also, I find the principle rather vague. But, I do realize that the acronym is catchy and that mentioning it might lead to a greater adoption in some circles.

From https://www.force11.org/group/fairgroup/fairprinciples :

```
A1.2 the protocol allows for an authentication and authorization procedure, where necessary.
```

**Comment by jhammock** [comment]
Training social network for basic data tools supporting reproduceability; aimed at scientists without coding experience- OpenRefine, intro to Python, SQL and R, etc.: https://datacarpentry.org/

**Comment by fdschneider** [comment]
Concerning FAIR and OPEN: You could include our best-practice guidelines for publishing trait data from the ETS website and Supplementary matarial of our paper. You can either 

- point to the ETS website URL  https://terminologies.gfbio.org/terms/ets/pages/bestpractice.html 

or

- duplicate the guidelines on the OTN website. I won't have the time to migrate that myself but you can pick everything from: https://github.com/EcologicalTraitData/ETS/blob/master/bestpractice.Rmd

**Comment by fdschneider** [comment]
Also, there is my [traitdataform](https://ecologicaltraitdata.github.io/traitdataform/) package assisting with harmonizing trait data into the ETS scheme.  CRAN link https://CRAN.R-project.org/package=traitdataform

**Comment by rachaelgallagher** [comment]
thanks @fdschneider this is a good one to add

**Comment by jhpoelen** [comment]
We now have a dedicated, editable, Resources page, so please add your linked content using the "edit" link in the OTN Resources page at:

http://opentraits.org/resources.html

Closing issue.
