### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by BErfanian** [open-traits-network/open-traits-network.github.io#100]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: b.erfanian
name: Mohammad Bagher Erfanian
email: b.erfanian@um.ac.ir
homepage: https://www.researchgate.net/profile/Mohammad_Bagher_Erfanian
lat: 36.312190
long: 36.312190
affiliation: Quantitative Plant Ecology and Biodiversity Research Lab., Faculty of Science, Ferdowsi University of Mashhad, Mashhad, Iran 
github: BErfanian
---

Bagher is a plant ecologist based in Mashhad Iran. 

## Collaboration statement
I enjoy working on applied Ecology. Especially, I am interested in disturbance ecology and evaluating how different human-mediated disturbances shape plant communities and change their features.

I could offer my expertise in the diverse approach in biodiversity (SD, PD, and FD) calculation and contribute trait data from my area. As an early career researcher, I'm always looking for new challenges.


```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
I've added your information and your profile is now visible on opentraits.org!  Welcome to the team!

**Comment by BErfanian** [comment]
@bmaitner Thanks, Would you please modify my lat/long, it is not correct in the opentraits.org

**Comment by bmaitner** [comment]
I think I've fixed it and it should be correct now.  Let me know if anything else needs updating!

**Comment by jhpoelen** [comment]
@BErfanian @benquist glad to hear that the location got updated.

Please note that if you reference the issue number with a ```#``` in front of it (e.g., #100 ) in your commit message, then the commit automatically appears in the issue as a link. I find this very useful to relate the changes made to a specific issue.

**Comment by jhpoelen** [comment]
I sounds mention that I often forget mentioning an issue number in a commit message, so the comments is a bit of a reminder for myself ; )
