### ISSUE TITLE
Nominating Rachel for AoB Plants Award  

### ISSUE THREAD

**Issue by hoganhaben** [open-traits-network/open-traits-network.github.io#101]
Hi OTN, 

On behalf of the OTN, and for the work put in with respect to this effort, I would like to nominate Rachel for the [AoB Plants Early Career Open Science Award](https://buckleylab.ucdavis.edu/aobp/aobp-ecos-awards/).  Rachel is aware that she will be nominated.

If you would like to participate in this, you can by, 1) approving the nomination, 2) editing the letter I have written.  

[AoBp Gallagher nomination for ECOS.docx](https://github.com/open-traits-network/open-traits-network.github.io/files/4232380/AoBp.Gallagher.nomination.for.ECOS.docx)

Guidelines are
-  500 words for the nomination text / letter.  
- Up to 5 visuals  
- page with references / links

Thanks for the help, 
Aaron

**Comment by jhpoelen** [comment]
@hoganhaben excellent! When would you like this by?

**Comment by hoganhaben** [comment]
@jhpoelen The deadline for nominations is March 31.

**Comment by rachaelgallagher** [comment]
Thanks @hoganhaben and @jhpoelen - I really appreciate your support!

**Comment by hoganhaben** [comment]
Hi all, 
Can we get this moved forward, please?  

@jhpoelen / others  could you please have a look at the letter / edit anything you would like 
@rachaelgallagher can you please sign the statement of approval  

I will get it into Tom Buckley at AOBP

Thanks, Aaron

**Comment by rachaelgallagher** [comment]
Thanks very much for writing this @hoganhaben - I'm so chuffed to be nominated and really appreciate your support. The OTN is very much a team effort, but I understand this is an individual based award so am very flattered to have you write such kind things about me.   Here's an edited version (note the extra 'a' in my Rachael). 

[AoBp.Gallagher.nomination.for.ECOS_RG.docx](https://github.com/open-traits-network/open-traits-network.github.io/files/4283839/AoBp.Gallagher.nomination.for.ECOS_RG.docx)

**Comment by hoganhaben** [comment]
Your welcome.  
Fingers crossed.

**Comment by jhpoelen** [comment]
@hoganhaben Thanks for moving this forward. You mentioned the deadline is March 31st. How exactly can I contribute to this effort? I quickly scanned the letter and it looks great.

**Comment by hoganhaben** [comment]
Thanks, @jhpoelen.  I have just gotten it submitted, so that'll do it.
