### ISSUE TITLE
BROT

### ISSUE THREAD

**Issue by julipausas** [open-traits-network/open-traits-network.github.io#104]
layout: dataset
id: brot
name: BROT
datasetDOI_URL: https://dx.doi.org/10.6084/m9.figshare.c.3843841
contactName: Juli Pausas
contactEmail: juli.g.pausas@ext.uv.es
license: 
traitList: 44 traits
higherGeography: Mediterranean Basin
decimalLatitude:
decimalLongitude:
taxon: Tracheophyta
eventDate: 
paperDOIcitation: 10.1038/sdata.2018.135
description:  A functional trait database for Mediterranean Basin plants
taxaList: 2457 taxa
usefulClasses: compilation from references and field data
dataStandard: Standardization of traits according to https://www.uv.es/jgpausas/brot.htm
standardizationScripts: 
webpage: https://www.uv.es/jgpausas/brot.htm
---
```

**Comment by jhpoelen** [comment]
Hey Juli @julipausas - Thanks for registering brot with the open traits network (see https://opentraits.org/datasets/brot and https://opentraits.org/datasets )! I hope that this registration will help make your trait datasets more visible and help connect with future collaborators around the world. Please let us know if you have ideas to improve the open traits network . -jorrit

**Comment by jhpoelen** [comment]
PS - If you'd like to add more information (e.g., usage examples, context) to your dataset on opentraits.org , please use the "edit" button on https://opentraits.org/datasets/brot and append information below the last ```---``` .
