### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by marimoracross** [open-traits-network/open-traits-network.github.io#105]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: marimoracross
name: María Mora Cross
email: mariamoracross@gmail.com
homepage: http://crbio.cr
lat: 9.972377 
long:-84.132958

affiliation: Costa Rica Institute of Technology (ITCR), Computer Engineering School 
National Biodiversity Institute of Costa Rica (INBio)
github: https://github.com/marimoracross
---

Maria is a Biodiversity Informatics specialist based in Heredia, Costa Rica. 

## Collaboration statement
I enjoy working on applied problems in biodiversity conservation using computer science algorithms and software tools. 

I can offer expertise in machine learning, big data, data mining and capacity building. I have applied some of these topics in my research projects and recently I received a one-year training at ITCR on these topics. My interest is to use the knowledge acquired to apply it in the extraction of traits from specimens and scientific publications about Costa Rica biodiversity.

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hey Maria @marimoracross  - thanks for registering with the open traits network (OTN). I hope you'll get the chance to collaborate with other OTN members . Actually, I am interested to hear how you are combining occurrence data with trait data. . . have you done any work on that? What tools are you using?

**Comment by jhpoelen** [comment]
btw - your member profile is available via http://opentraits.org/members/marimoracross .

**Comment by marimoracross** [comment]
Hi Jorrit:

Thank you for including me in OTN.

I do not get there yet ("combining occurrence data with trait data") but
what I would like to do is create a multidimensional database with traits
as one or more dimensions to access the CRBio portal database in this way.

Saludos,

Maria

**Comment by rachaelgallagher** [comment]
Welcome Maria! I have been combining traits with occurrences in the Australian flora. Sounds like you have some great skills - hopefully we can share some knowledge via the OTN. I'd actually like to pursue the idea of the OTN website offering tutorials (or similar) of approaches to common analytical problems. Perhaps we can start a working group once we've more members on board!
Rachael

Dr Rachael Gallagher

ARC DECRA Fellow
Deputy Chair, NSW Threatened Species Scientific Committee

Macquarie University
Department of Biological Sciences


Plants = Life

________________________________

**Comment by marimoracross** [comment]
Thanks Rachel, it sounds like a very good idea!. I would like to know more
about your experience combining trait data with occurrences.

My best regards,
