### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by JeromeMathieuEcology** [open-traits-network/open-traits-network.github.io#107]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: jerome-mathieu
name: Jerome Mathieu
email: email.jussieu@gmail.com
homepage: http://www.jerome-mathieu.com/
lat: 48.846661
long: 2.356262
affiliation: Institute of Ecological and Environmental Sciences - Paris, Sorbonne University 
github: JeromeMathieuEcology
---

Jerome works mostly on soil organisms

## Collaboration statement
I enjoy performing comparative analyses of animals. So far, I worked mostly on soil organisms, especially earthworm. For instance, I released a global database on ontogenic growth of this group (EGrowth), with a GUI (in Shiny) to explore the database. Everything is on GitHub. I am about to release another version about reproductive traits of earthworm. 

I am currently developing a database on ecological stoichiometry of terrestrial animals.
I can offer expertise in data management and reproducible workflow in R.

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by rachaelgallagher** [comment]
Hi @JeromeMathieuEcology - thanks for joining the OTN! Welcome. It's great to have someone working with soil organisms, there's plenty of scope for creating a trait handbook for this group if that's something you'd like to pursue? the idea of the OTN is that you can build nodes of similar expertise by encouraging others working in your area to join and share knowledge.

**Comment by JeromeMathieuEcology** [comment]
Hi Rachael,

Glad to see that soil organisms interest not soil ecologists!
Indeed, I'd like to develop a database about demographic traits of soil
invertebrates.
Thanks for the info and for the effort of maintaining the network.

All the best,
Jerome
