### ISSUE TITLE
Please add EGrowth to the OTN dataset registry

### ISSUE THREAD

**Issue by JeromeMathieuEcology** [open-traits-network/open-traits-network.github.io#108]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: egrowth
name: EGrowth
datasetDOI_URL: https://zenodo.org/record/1039952
contactName: Jerome Mathieu
contactEmail: email.jussieu@gmail.com
license: CC BY
traitList: Body mass of earthworm individuals during ontogenic growth (growth curves)
higherGeography: Global
decimalLatitude:
decimalLongitude:
taxon: Oligochaeta
eventDate: about 1900 to 2016
paperDOIcitation: 10.1016/j.soilbio.2018.04.004
description: The EGrowth database contains 1073 growth curves of 51 species of earthworms, representing 16002 measures of body mass. It covers publications on earthworm body size from 1900 to 2016. The environmental conditions in which the growth curves were produced are also reported (e.g. temperature, pesticides).
taxaList: 51 species
usefulClasses: Mostly in-lab measurements
dataStandard:
standardizationScripts: https://github.com/JeromeMathieuEcology/EGrowth/tree/v1.0.1
webpage: https://zenodo.org/record/1039952
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by jhpoelen** [comment]
@JeromeMathieuEcology thanks for your application to register EGrowth to the Open Traits Network. 

@jmadin josh - would you like to review and register this dataset? Happy to help with logistics if needed.

**Comment by jhpoelen** [comment]
Thanks again @JeromeMathieuEcology for registering EGrowth with the Open Traits Network. The dataset has been added and is available at http://opentraits.org/datasets/egrowth . Thank you for your patience and please use the "update" link to add or update information to your dataset entry.
