### ISSUE TITLE
apply consistent style to opentraits.org pages

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#11]
Currently, we have the original opentraits.org pages mixed with membership (#3) and dataset registry (#4) pages . 

Proposed is to somehow link the pages and apply a consistent style so that https://opentraits.org comes across as inviting and organized. 
 
Here's the section on "theme's" in the Jekyll documentation: https://jekyllrb.com/docs/themes/ .

**Comment by jmadin** [comment]
@jhpoelen were you thinking of using a prebaked theme? Or trying to match the old theme?

**Comment by jhpoelen** [comment]
@jmadin I'd say: pick a scheme, not necessarily the current one, that would be fun to work with, easy to maintain and nice to look at, especially for the person (you?) that would be working on it.  I am assuming that the open traits logo, links, forms (e.g., email contact form) and the text would be re-used. 
 
Perhaps others like @rachaelgallagher have some opinions about this.

**Comment by jhpoelen** [comment]
@jmadin is this something that you'd like to take on?

**Comment by jmadin** [comment]
Yes -- doing it now.

**Comment by jmadin** [comment]
@bmaitner @jhpoelen 
Hi guys.  I'm working on the structure.  Who create the "member" files?  They look autogenerated. If they are autogenerated, we need to add `layout: member` to the file metadata (preferably the very top). I've create a "layout" for member pages. Also, adding "email" would be handy for contact. 

We will also need `layout: dataset` in for the dataset files (same as per above). Who is creating these? Is it @caterinap

**Comment by bmaitner** [comment]
@jmadin , I believe the member files were created by @iimog and @silviapine (per comments on #3  )

Email is one of the fields @iimog has been using, but it wasn't one of the fields that @iimog  and @silviapine  populated for everyone.  I think only a few folks have added this information to their profiles.

**Comment by jmadin** [comment]
Thanks, Brian. Good point about email. 

Are we ready to start putting all this together?  Or do we want to keep the current splash page until we feel the site is ready?  

I've mocked up something workable on my fork. Pretty basic layout, but that's okay, right? Can always update that later.  

I believe you were working on putting people on maps. If you have the google map API with the site, perhaps you could push that.

**Comment by jhpoelen** [comment]
@jmadin @bmaitner I'd say lets start pushing changes  . . . there's not that many folks using the site now and it'd be a nice way to get feedback and move forward.

**Comment by jmadin** [comment]
Sure thing -- you want to make me a collaborator?  Might speed things up not having to okay every pull request.

**Comment by jhpoelen** [comment]
@jmadin I've added you as a collaborator, please confirm you can now push to master directly. 

Also, I use pull requests to solicit input from others, let others know about (big) changes and build consensus. And I agree that small incremental changes are sometimes not worth making a pull request for.

**Comment by jmadin** [comment]
@jhpoelen I have a lot of changes.  I've not up-to-date on the best approaches with git -- how would you suggest I proceed?  Perhaps a pull-request is better in this case?

**Comment by jhpoelen** [comment]
maybe for the first big one? I'd be happy to help test.

**Comment by rachaelgallagher** [comment]
@jhpoelen @jmadin @bmaitner thanks for your work on this. I agree that a neat and simple pre-made theme is a good idea here. I certainly don't want to recreate the previous theme of the wordpress site and prefer something along the lines of what you've achieved for GloBI @jhpoelen

**Comment by jmadin** [comment]
I would like to merge the information in the home and about pages, and then remove the about page to simplify the menu options.

**Comment by jmadin** [comment]
@bmaitner do we want to continue using the subscription page?  Or should we remove it and have people subscribe by adding a member page in GitHub?

**Comment by bmaitner** [comment]
> @bmaitner do we want to continue using the subscription page? Or should we remove it and have people subscribe by adding a member page in GitHub?

+1 for removing it and having folks subscribe via the member pages

**Comment by jmadin** [comment]
Subscript page is now gone; about page gone as well. Rather simple site. I will close this issue off now. However, we can easily change the theme in the future - as we're using the generic "minima" theme currently. Open another issue if you want a new theme.
