### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by rbslandau** [open-traits-network/open-traits-network.github.io#110]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: ralf-b-schaefer
name: Ralf B. Schaefer
email: schaefer-ralf@uni-landau.de
homepage: www.landscapecology.uni-landau.de
lat: 49.218726
long: 8.115037
affiliation: Institute for Environmental Sciences, University of Koblenz-Landau, Landau, Germany 
github: rbslandau
---

Ralf is an aquatic stress ecologist based in Landau, Germany.

## Collaboration statement
I work on the responses of microbial and invertebrate communities, predominantly in freshwater ecosystems, to anthropogenic stressors. I have been involved in assembling an Australian trait database for invertebrates (https://ausrivas.ewater.org.au/index.php/resources2/category/4-software-downloads - see paper: https://doi.org/10.1016/j.ecolind.2020.106280) and I am leading a project to unite aquatic invertebrate databases from different continents, where a first version will be ready in the coming months.

I can offer expertise in assembling and cleaning trait data from different sources - we are currently writing a paper how different decisions to aggregate affect the outcome of analyses - and am happy to provide data etc. for larger analyses across organism groups or actually lead such analyses. Also would be happy to host visitors in my group and organise - perhaps virtual - meetings

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi Ralf,

Your profile is now visible on the Open Traits website ( http://opentraits.org/members/ralf-b-schaefer  ).  Great to have another non-plant person in the group, especially one with data cleaning expertise!  It might be useful to try to get a group together at some point to discuss how we might share some code or write a package to save us all from reinventing the wheel.

Also, it would be great to have your Australian invertebrate dataset listed on the datasets page.  If you have time, it would be great if you could fill out a form for that as well (https://github.com/open-traits-network/open-traits-network.github.io/issues/new?assignees=open-traits-network%2Feditors&labels=dataset+review&template=register-dataset.md&title=Please+add+%5Bname%5D+to+the+OTN+dataset+registry) 

Thanks for joining and welcome aboard!
