### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by lembrechtsjonas** [open-traits-network/open-traits-network.github.io#113]
I'm happy to do some occassional editing and introducing of new datasets!

**Comment by jhpoelen** [comment]
Hi @lembrechtsjonas thank you for offering your time and expertise! Your contributions will help to make OTN more sustainable by spreading out the work needed to maintain our registries and to engage colleagues and peers. 

I'll share this same message with a fellow volunteer (see #115 @BErfanian) . . . perhaps you can collaborate and get started together! 


Here's an idea on how to get started: please review the editorial steps for adding members and datasets by having a peek at editorial work (see e.g., #61 and #93 ). The instructions are listed at the bottom of the respective initial issue comment. Then, you can start watching the issues at https://github.com/open-traits-network/open-traits-network.github.io/issues and self-assign the issue you'd like to work on. 

@rachaelgallagher @jmadin @bmaitner please let me know if there's anything you'd like to add.

**Comment by rachaelgallagher** [comment]
Thanks @lembrechtsjonas ! We appreciate your offer of help and think it's a really valuable way for you to help build the activities of the OTN. We have some legacy datasets which need to be integrated into the trait registry and you are also more than welcome to identify other open datasets of traits fro any organisms that we can register. We're planning a hackathon to work towards a programmatic solution to combining datasets in coming months as well.

**Comment by jhpoelen** [comment]
Hey @lembrechtsjonas I've invited you to join the "junior editor" team. Here you can exchange ideas with fellow aspiring editors that are getting familiar with the OTN editorial process.
