### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by BErfanian** [open-traits-network/open-traits-network.github.io#115]
Hi! 
I'm available for editing datasets.

**Comment by jhpoelen** [comment]
Hi @lembrechtsjonas thank you for offering your time and expertise! Your contributions will help to make OTN more sustainable by spreading out the work needed to maintain our registries and to engage colleagues and peers. 

I'll share this same message with a fellow volunteer (see #113 @lembrechtsjonas) . . . perhaps you can collaborate and get started together! 


Here's an idea on how to get started: please review the editorial steps for adding members and datasets by having a peek at editorial work (see e.g., #61 and #93 ). The instructions are listed at the bottom of the respective initial issue comments. Then, you can start watching the issues at https://github.com/open-traits-network/open-traits-network.github.io/issues and self-assign the issue you'd like to work on. 

@rachaelgallagher @jmadin @bmaitner please let me know if there's anything you'd like to add.

**Comment by BErfanian** [comment]
Hi @jhpoelen, 
Thanks, 
I want to work on issue  #117, but following this [guidlines](https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users), I could not find any checkbox next to the issue. Sorry if this is an easy question, I'm a fast learner, so, it won't take a long time learning these editoring stuffs. 
Bagher

**Comment by jhpoelen** [comment]
Hi @BErfanian  Thanks for reaching out! 

If you'd like to assign an issue to yourself. You can click "self-assign" (see attached image) button in top right next to the issue. If you can't see the button, please let me know. If this doesn't help, please describe in detail what you'd like to accomplish and which editorial steps you were able to complete. Providing screenshots often help.

If this wasn't helpful, please offer suggestions on how we can improve documenting our editorial  workflow.

![Screenshot from 2020-04-16 20-03-18](https://user-images.githubusercontent.com/1084872/79527982-bbb79900-801d-11ea-9e60-4ae2c1f9a0bb.png)

**Comment by BErfanian** [comment]
Hi @jhpoelen,
I can't see the button!
![Picture1](https://user-images.githubusercontent.com/7317006/79593093-30f39e80-80f0-11ea-87d7-9cf6c9a5a970.png)

**Comment by jhpoelen** [comment]
Hi @BErfanian ! Thanks for your message and for providing the screenshot. 

If you click on the issue you'd like to work on (e.g., issue #117), you should see the button. Please confirm.

**Comment by BErfanian** [comment]
Dear @jhpoelen, 
I follow the [guideline](https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users), 
 No checkbox is shown for me whether I click on the issue or not. 
![Picture1](https://user-images.githubusercontent.com/7317006/79604027-a5373d80-8102-11ea-8eb1-00966bfeea6d.png)
When I click on the issue, the page become open! Have a look at the attached photos
![Picture2](https://user-images.githubusercontent.com/7317006/79604307-11b23c80-8103-11ea-9945-41d12b954533.png)

**Comment by jhpoelen** [comment]
Hi @BErfanian - Thank you for being patient. After reading your message, I realized that only members or people that comment on an issue can assign themselves to an issue. This is why I have created a group "junior editors" and invited you as a member. Once you accept the invitation, you'll have read permission and should be able to assign issues to yourself. Please confirm. 

@rachaelgallagher @jmadin @bmaitner I imagine that junior editors are editors that are learning to add and review OTN member / datasets and propose additions via pull requests.

**Comment by BErfanian** [comment]
Thanks for adding me as a new editor.
