### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by JonathonMifsud** [open-traits-network/open-traits-network.github.io#117]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: jonathon-mifsud
name: Jonathon Mifsud
email: jonathon.mifsud1@hdr.mq.edu.au
homepage: https://www.researchgate.net/profile/Jonathon_Mifsud
lat: -33.77403
long: 151.115978
affiliation: Department of Biological Sciences, Macquarie University, Sydney, NSW, Australia 
github: JonathonMifsud
---
Jonathon is a Master of Research student based in Sydney, Australia. I am currently examining interactions between plant ecology and virus dynamics. I have broad interests in informatics, infectious disease, evolutionary biology and all things R. 
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by BErfanian** [comment]
Hi @JonathonMifsud, 
Thank you for joining the Open traits network, 
Here is a link to your profile: 
http://opentraits.org/members/jonathon-mifsud
