### ISSUE TITLE
I'd like to be an editor

### ISSUE THREAD

**Issue by JonathonMifsud** [open-traits-network/open-traits-network.github.io#127]
Hi,

Thank you for the welcome, if you require any more editors I would like to help out!

Cheers,

**Comment by rachaelgallagher** [comment]
Welcome Jon! Don't I know you from somewhere?? :) Thanks for joining. We (@jhpoelen @bmaitner @jmadin) are discussing some options for training 'junior' editors for the OTN just now.

**Comment by jhpoelen** [comment]
Hi @JonathonMifsud . I just sent you an invite to join the "junior editors" team. The idea is that you can self-organize with other member and learn how to go through the OTN editorial process. I am sure there's a lot of documentation and guidance that can be added, and I hope that you , and others part of that group can play a big role in shaping this.

**Comment by JonathonMifsud** [comment]
Thank you @rachaelgallagher @jhpoelen looking forward to it!
