### ISSUE TITLE
use consistent image path

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#13]
Right now, we have two locations for image paths: ```/assets/img``` and ```/images```. 

Suggest to use a single folder to put images is. I'd favor ```/images``` . 

Related to https://github.com/open-traits-network/open-traits-network.github.io/pull/12 .

**Comment by bmaitner** [comment]
+1

**Comment by jhpoelen** [comment]
@iimog @bmaitner I took the liberty to apply a consistent image page. I moved assets/img/ -> images/ and updated related references in leaflet style sheet, README instructions and @iimog 's member profile . Please comment or re-open if you have any issues with this: happy to apply other scheme.

**Comment by iimog** [comment]
Thanks
