### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by fisw10** [open-traits-network/open-traits-network.github.io#130]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: franziska-schrodt
name: Franziska Schrodt
email: franziska.schrodt1@nottingham.ac.uk
homepage: https://fischrodt.wixsite.com/fisw
lat: 52.939848
long: -1.195059
affiliation: School of Geography, University of Nottingham, UK 
github: fisw10
---

Franziska is a numerical macroecologist based in Nottingham, UK 

## Collaboration statement
My work focuses on the application of remote sensing, machine learning and non-linear statistical tools to study biogeochemical patterns. I am especially interested in plant functional trait - environment correlations and associated implications for ecosystem structure and functioning.

I can offer expertise in robust inference of missing traits and multivariate trait diversity measures. I am also happy to help connect people together around traits by running working groups, hosting visitors in my lab and organising symposia at conferences. For example, I gave a workshop on trait imputation at one of the British Ecological Society macroecology meetings based on the machine learning method I co-developed: https://github.com/fisw10/BHPMF

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by JonathonMifsud** [comment]
Hi @fisw10 - thanks for joining the OTN! Your profile has been added and can be view here: https://opentraits.org/members/franziska-schrodt

**Comment by JonathonMifsud** [comment]
Hi @jhpoelen is this okay to close? I will make sure to reference the issue in the commit next time!

**Comment by jhpoelen** [comment]
@fisw10 Welcome! Just curious - how did you learn about the Open Trait Network ? 

@JonathonMifsud congratulation on your first (?) contribution to editing the OTN member registry.

**Comment by rachaelgallagher** [comment]
@fisw10 great to have you on board Franziska! Perhaps you are working with Dorren Boyd at U Nottingham? Either way, your work sounds great and I'd love to hear more about it sometime. Rachael 

Great work @JonathonMifsud - you're off and running now :) go ahead and close.
