### ISSUE TITLE
Please add BETYdb to the OTN dataset registry

### ISSUE THREAD

**Issue by dlebauer** [open-traits-network/open-traits-network.github.io#145]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: betydb
name: BETYdb
datasetDOI_URL: https://betydb.org
contactName: David LeBauer
contactEmail: dlebauer@arizona.edu
license: ODC-By
traitList: Over 50k plant traits and ecosystem functions from over 5k taxa
higherGeography: Global | Africa | Antarctica | Asia | Europe | North America | Oceania | South America
decimalLatitude:
decimalLongitude:
taxon: Plantae
eventDate: about 1910 to current
paperDOIcitation: 10.1111/gcbb.12420
description: A database of plant traits and ecosystem services. Designed to support meta-analysis and crop and ecosystem modeling.
taxaList: 279,875 plant taxa, standardized mainly based on The Plant List
usefulClasses: Mostly in-situ measurements on plant individuals, communities, and ecosystems
dataStandard: Standardization of taxonomy using usda.plants.gov; no standardization of traits vocabulary
standardizationScripts: None
webpage: https://www.betydb.org
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by JonathonMifsud** [comment]
Hi @dlebauer, thank you for sharing this dataset with OTN. You can find registered on the OTN page here: https://opentraits.org/datasets/betydb

**Comment by JonathonMifsud** [comment]
Hi @jhpoelen, as this is my first dataset registration I would just like to confirm with you that everything is correct, cheers!

**Comment by jhpoelen** [comment]
Hey @JonathonMifsud congrats on helping @dlebauer register their dataset plant trait database. I look at the page and I noticed that the paperDOIcitation  ```10.1111/gcbb.12420``` link creates page 404 not found, even though it appears to be a valid doi. Perhaps the code that creates the doi link https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_layouts/dataset.html  needs a little attention? Or maybe the form wasn't filled out properly? 

Curious to hear what you think should be done.

**Comment by jhpoelen** [comment]
Perhaps you can ask @BErfanian whether he has some ideas.

**Comment by JonathonMifsud** [comment]
The paperDOIcitation looks correct and matches the database paper:  https://onlinelibrary.wiley.com/doi/abs/10.1111/gcbb.12420. Other OTN registered databases seem to have a similar problem e.g. [BROT](https://opentraits.org/datasets/brot) and [EGrowth](http://opentraits.org/datasets/egrowth). The DOI works if `https://www.doi.org/` is added they link correctly https://www.doi.org/10.1111/gcbb.12420

I notice that the paperDOIcitation code expects a web link (href) could this be the problem?

Hi @BErfanian, let me know if you have any thoughts on this.

**Comment by BErfanian** [comment]
Hi @JonathonMifsud, Sorry for the delay, I was on field trips. For the paper DOIcitation, we add `https://www.doi.org/` before each code. This should be edited for those datasets that their paperDOIcitatin section is not working properly. Would you please edit those datasets (e.g. [BROT](https://opentraits.org/datasets/brot) and [TRY](https://opentraits.org/datasets/TRY)), too?

**Comment by JonathonMifsud** [comment]
Hi @BErfanian, all datasets have now been checked and updated (I didn't reference this issue after the first 4 datasets to avoid spam). I think asking new database owners to add this is a good suggestion.

**Comment by jhpoelen** [comment]
@JonathonMifsud Thanks for making this happen!
