### ISSUE TITLE
Database of Plant Heat Tolerance

### ISSUE THREAD

**Issue by tmoreperez** [open-traits-network/open-traits-network.github.io#156]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: DPHeaT
name: Database of Plant Heat Tolerances
datasetDOI_URL: https://github.com/tmoreperez/DPHeaT
contactName: Timothy M. Perez
contactEmail: t.more.perez@gmail.com
license: CC BY
traitList: Heat tolerance estimates for 123 species
higherGeography: Global |  North America
decimalLatitude: 25.677
decimalLongitude: -80.275
taxon: Pteridophytes, Gymnosperms, Angiosperms
eventDate: 2018
paperDOIcitation: 10.1111/jbi.13984
description: A growing database of plant heat tolerances, primarily for photosynthetic tissues, quantified in terms of temperatures causing a pre-determined level of damage. The present database contains Tcrit and T50 heat tolerance estimates corresponding to the temperatures that cause initial and 50% damage to maximum quantum yield.
taxaList: 123 species names based on the Taxonomic Name Resolution Service
usefulClasses: Heat tolerances of plants growing outdoors in a common garden environment in Miami, FL
dataStandard: Heat treatment duration: 15 minutes, Recovery time: 24 hours, Damage assessed with maximum quantum yield (Fv/Fm) fluorescence; standardization of taxonomy mainly based on http://www.theplantlist.org/
standardizationScripts: NA
webpage: https://github.com/tmoreperez/DPHeaT
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by jhpoelen** [comment]
@tmoreperez thanks for registering the "Database of Plant Heat Tolerance" with the Open Traits Network. Very neat to see how you are using github to host the database: https://github.com/tmoreperez/DPHeaT . 

Your valuable database can now be found via https://opentraits.org and https://opentraits.org/datasets/dpheat . Please review and comment/re-open this issue if you'd like to make additional changes. Also, you can always update your own database entry by clicking on the "edit" link in the dataset page.
