### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by wcepverberk** [open-traits-network/open-traits-network.github.io#165]
layout: member
id: wcepverberk
name: Wilco C.E.P. Verberk
email: wilco@aquaticecology.nl
homepage: www.aquaticecology.nl
lat: 51.824024
long: 5.868087
affiliation: Department of Animal Ecology and Physiology, Radboud University, Nijmegen, The Netherlands.
github: wcepverberk
---

Wilco is a ecophysiologist working on aquatic ectotherms based in Nijmegen, The Netherlands. 

## Collaboration statement
I enjoy analysing on physiological traits (metabolic rate, thermal tolerance) and life-history traits (growth, development, body size). My work focuses on aquatic insects and other (aquatic) ectotherms. I support initiatives for the synthesis of trait informations and hope to do more work on this in the near future.

**Comment by jhpoelen** [comment]
Hoi Wilco - 

Welkom bij 't Open Trait Network (OTN). I've just added your member profile to the OTN directory  and hope you'll connect to follow trait researchers from around the world (and Amsterdam @jellers1) and find ways to make it easier to re-use and integrate valuable trait data.

groetjes,
-jorrit

PS your profiles is available at @wcepverberk for your review . Changes can be submitted via the "edit page" link or by submitting an issue.
