### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by jellers1** [open-traits-network/open-traits-network.github.io#166]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: Jacintha Ellers
name: Jacintha Ellers
email: j.ellers@vu.nl
homepage: https://www.amsterdamecology.nl/principal-investigators/jacintha-ellers/
lat: 52.33441
long: 4.86572
affiliation: Department of Ecological Science, Vrije Universiteit Amsterdam, Amsterdam, The Netherlands 
github: jellers1
---

Jacintha is a evolutionary ecologist based in Amsterdam, The Netherlands. 

## Collaboration statement
I am interested to understand the evolution of traits as a joint interplay of genes, genome, and environment. My primary contribution to trait ecology is the Handbook of protocols for standardized measurement of terrestrial invertebrate functional traits - published in Functional Ecology (Moretti et al 2017). 

I would be happy to collaborate on collecting physiological and life history trait data, and analyse these in a comparative and evolutionary framework. Most of my work is on arthropods (parasitoids, drosophila, Collembola) and other ectotherms (lizards, frogs), but keen to learn about new groups. 

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hoi Jacintha - 

Welkom bij the Open Traits Network. I've just added your information to https://opentraits.org/members/jacintha-ellers and you are now included in the member directory! 

I also noticed that a fellow Dutch person, from Nijmegen, also decided to join open traits network just before you (see @wcepverberk, https://opentraits.org/members/wcepverberk, https://github.com/open-traits-network/open-traits-network.github.io/issues/165) . A coincidence?

groetjes,
-jorrit

**Comment by jellers1** [comment]
Hoi Jorrit,
Indeed this is no coincidence, Wilco and I are working on a grant application for trait database project together. If funded we hope to connect it with the Open Traits network.

Cheers,
Jacintha

(Ben jij Nederlands? Of heb je een tijdje in Nederland gewerkt?)

**Comment by jhpoelen** [comment]
@jellers1 @wcepverberk good luck with your grant application! 

And yes, I am Dutch (geboren en getogen - echt wel!) and have lived and worked in the US for over a decade.
