### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by sjryan3** [open-traits-network/open-traits-network.github.io#169]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: sjryan3
name: Sadie J. Ryan
email: sjryan@ufl.edu
homepage: https://www.sadieryan.net
lat: 29.63760527109054
long:  -82.3520265424835
affiliation: Department of Geography and the Emerging Pathogens Institute, University of Florida, Gainesville, FL 32601
github: sjryan3
---

Sadie is a Medical Geographer in Florida

## Collaboration statement
I enjoy working on multiple projects exploring the human-wildlife interface, in disease ecology and conservation. I am part of several teams conducting large-scale data synthesis and modeling to explore disease vector traits, dynamics, and how those relate to our changing world. 

I am not an expert coder, by any means, but I can provide input on the processes of database set up, how to think about communicating best practices and workflows to the less familiar crowds; be this in the form of collaborative workshops, seminars, collaborative publications, blog posting, etc. I see myself as a facilitator and connector, with the experience of working across many collaborative projects.

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hi Sadie @sjryan3 -

Welcome to the Open Traits Network! You can find your member page at http://opentraits.org/members/sadie-j-ryan . If you'd like to update your information you can use the "edit" button to create a change request (aka pull request) or just open another issue at https://github.com/open-traits-network/open-traits-network.github.io/issues/.

And . . . how exciting that you are a medical geographer, facilitator and connector! 

I noticed that you are working at the Emerging Pathogen department and have experience in compiling datasets / databases. 

One of the projects I am working on is Global Biotic Interactions (GloBI, https://globalbioticinteractions.org , https://opentraits.org/datasets/globi). GloBI indexes species interaction datasets to make the existing datasets easier to discover and use. GloBI has already indexed many pathogen datasets (plant disease, parasite-host, virus-host) with more being indexed. 

Hopefully we'll get a chance to exchange notes on ways to help facilitate studying the ecology of pathogens through integrated social and data networks like OTN! 

-jorrit
