### ISSUE TITLE
I'd like to ... sort out the warnings when accessing the site

### ISSUE THREAD

**Issue by Daniel-Mietchen** [open-traits-network/open-traits-network.github.io#179]
When trying to access https://opentraits.net/ (latest Firefox under latest Ubuntu), I am getting this error message, presumably due to some expired certificates:

![Screenshot from 2022-06-27 19-49-50](https://user-images.githubusercontent.com/465923/176004329-37140b96-e1af-430f-be38-0c6495456179.png)

**Comment by Daniel-Mietchen** [comment]
Seems this is due to the current URL provided at
https://github.com/open-traits-network/open-traits-network.github.io
pointing to [opentraits.net](https://opentraits.net/) instead of [opentraits.org](https://opentraits.org/):
![Screenshot from 2022-06-27 20-32-34](https://user-images.githubusercontent.com/465923/176011700-80691a9a-f07b-404d-a00f-844a93e61ab5.png)

**Comment by jhpoelen** [comment]
@Daniel-Mietchen thanks for sharing - the opentraits.net should be changed to opentraits.org . Do you mind doing it?

**Comment by Daniel-Mietchen** [comment]
Done.

**Comment by jhpoelen** [comment]
Thanks @Daniel-Mietchen !
