### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by Jegelewicz** [open-traits-network/open-traits-network.github.io#182]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: jegelewicz
name: Teresa J Mayfield-Meyer
email: jegelewicz66@gmail.com
homepage: https://arctos.database.museum/agent/21300608
lat: 35.174562
long: -106.583685
affiliation: Arctos Collaborative Collection Management Solution 
github: jegelewicz 
orcid: https://orcid.org/0000-0002-1970-7044 
wikidata: https://www.wikidata.org/wiki/Q63834511
---

Teresa is a former accountant working with biodiversity data. 

## Collaboration statement
I work in a collaborative community developing a solution for managing museum collections data. I and my colleagues are always looking for ways to integrate our data with others to create "extended digital specimens".

I can assist with data normalization and clean up and also with introduction to a resource for storing both specimen based and observational trait data in a web-accessible tool. I would like to explore how the trait data held in our collective database could contribute to this project.


```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi @Jegelewicz your profile is now live at: https://opentraits.org/members/teresa-jegelewicz

Welcome aboard!

**Comment by jhpoelen** [comment]
@bmaitner thanks for welcoming @Jegelewicz to the Open Trait Network!

I've enjoyed collaborating with @Jegelewicz and their Arctos colleagues like @campmlc @dustymc . A great collection management community willing to experiment. . . and I am sure there's a bunch of trait data waiting to be used. 

Perhaps @Jegelewicz can share an example of a specimen that includes one or more traits  (e.g., body mass).

**Comment by Jegelewicz** [comment]
This record has a bunch of traits - we call them attributes - https://arctos.database.museum/guid/DMNS:Mamm:11098

![image](https://user-images.githubusercontent.com/5725767/176533117-6b430fc6-98b1-47a8-85e7-5689adf7d9bd.png)

The attributes available currently to Arctos catalog records can be found in our code table - https://arctos.database.museum/info/ctDocumentation.cfm?table=ctattribute_type

So you might find any of these associated with any number of records!

**Comment by jhpoelen** [comment]
@Jegelewicz thanks for sharing this example!

@bmaitner et al. How would you transform Teresa's wealth of traits into a data format that you could use? In other words, could you share an example on you'd transcribe the data shown by @Jegelewicz into some kind of tabular or other structure format?
