### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by Danielowusukwakye** [open-traits-network/open-traits-network.github.io#189]
layout: member
id: Daniel
name: Daniel Owusu Kwakye
email: danielow@post.bgu.ac.il
lat: 34 E
long: 30 N
affiliation: French Associate of Agriculture and Biotechnology of Drylands, Ben-Gurion University of the Negev,Israel. 
github: Danielowusukwakye

---
Plant Ecophysiologist in Ben Gurion University of the Negev, Israel. 

## Collaboration statement
interested in adaptation and acclimation of  plants to abiotic stresses and roots dynamics and functions and their role in whole plant tolerance to abiotic stress

**Comment by bmaitner** [comment]
HI Daniel,  thanks for updating the profile information.  Your profile is now live at: https://opentraits.org/members/daniel-owusu-kwakye

Glad to have you on board!
