### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by mlatvis** [open-traits-network/open-traits-network.github.io#191]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: maribeth-latvis
name: Maribeth Latvis
email: maribeth.latvis@sdstate.edu
homepage: https://maribethlatvis.wixsite.com/plantsyst
lat: 44.3206
long: -96.7853
affiliation: Department of Natural Resource Management, South Dakota State University, Brookings, SD, USA
github: mlatvis
orcid: https://orcid.org/0000-0003-2496-7753
---

Maribeth is a plant systematist based in Brookings, South Dakota, USA.

## Collaboration statement
I apply evolutionary history (phylogenies) to understand patterns of species relationships, community assembly, and trait evolution. As Director of the CA Taylor Herbarium (SDC), I am interested in creating an Extended Specimen Network for our prairie species that links specimens to related metadata (locality, data, genetic, trait). Many species used in plant restoration have very little available trait data, and I would be interested in filling this gap. 


```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi Maribeth!  Your profile is now active at https://opentraits.org/members/maribeth-latvis .  Welcome aboard!  I love the extended specimen network concept, as this seems like a sort of "gold standard" for biodiversity data!
