### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by seltmann** [open-traits-network/open-traits-network.github.io#196]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: katja-c-seltmann
name: Katja C Seltmann
email: seltmann@ucsb.edu
homepage: https://www.begoniasociety.org
lat: 34.419636
long: -119.854645
affiliation: Cheadle Center for Biodiversity and Ecological Restoration, University of California - Santa Barbara
github: seltmann
orcid: https://orcid.org/0000-0001-5354-6048
wikidata: 
---

Katja is an insect biologist working in Santa Barbara California.

## Collaboration statement
I enjoy working on bees and other insects and publishing research about insect biodiversity, biodiversity data science, and insect responses to environmental changes or conditions. I presently am coordinating a project called [Big Bee](http://big-bee.net) that examines bee traits from images. I can offer expertise in insect biology and natural history collection data and hope to connect people to the Big-Bee project via idea sharing, conversation, and research collaborations.




```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hi @seltmann Katja - Thanks for taking the time to register and sharing your collaboration statement. 

Your profile is available at https://opentraits.org/members/katja-c-seltmann .

Looking forward to getting your bee traits and more connected to OTN members, datasets and publications.
