### ISSUE TITLE
add group picture to Aug 2018 New Orleans workshop

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#2]
as suggested by @shandongfx -

![workshop_photo](https://user-images.githubusercontent.com/1084872/63530060-98524380-c4ba-11e9-95b0-edef0eb28416.jpg)

**Comment by jmadin** [comment]
I added the picture to the post about the workshop in New Orleans. 
[https://opentraits.org/update/2018/06/01/first-workshop-esa.html](https://opentraits.org/update/2018/06/01/first-workshop-esa.html)
