### ISSUE TITLE
I'd like to ... be able to reference the Leipzig sDiv workshop

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#202]
Hi! 

@chiras @iimog - can you please provide some reasonable stable URL that contains content describing the upcoming sDiv trait workshop? 

Perhaps a news item similar to https://opentraits.org/update/2022/06/21/open-traits-network-2022-virtual-meeting.html ?

Thanks!

**Comment by jhpoelen** [comment]
In discussion with @Daniel-Mietchen I've added a workshop page at:

https://opentraits.org/update/2022/07/25/sdev-traits-workshop.html

**Comment by Daniel-Mietchen** [comment]
The page at https://opentraits.org/update/2022/07/25/sdev-traits-workshop.html can still be updated with more of the information from https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_posts/2022-07-25-sdev-traits-workshop.md .

**Comment by Daniel-Mietchen** [comment]
Here is a first shot at a Scholia event page for the workshop: 
https://scholia.toolforge.org/event/Q113487331 .

The participation data in there is based on https://opentraits.org/update/2022/07/25/sdev-traits-workshop.html , which is incorrect in some ways, so I'd like to ask @rachaelgallagher and @seltmann whether and how they'd like to be listed.
