### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by PatrickPata** [open-traits-network/open-traits-network.github.io#205]
---
layout: member
id: patrick-r-pata
name: Patrick R. Pata
email: p.pata@oceans.ubc.ca
lat: 49.264
long:  -123.251
affiliation: Department of Earth, Ocean, and Atmospheric Sciences, University of British Columbia, Canada
github: PatrickPata
orcid: https://orcid.org/0000-0002-9704-7838
---

Patrick is a biological oceanographer focusing on zooplankton ecology and is based in Vancouver, Canada.

## Collaboration statement
I am most interested in the distribution and connectivity of marine communities and how this could aid in ocean management. I have aggregated a zooplankton traits dataset that expands the currently available global copepod trait datasets to include other zooplankton taxonomic groups and additional traits. I am currently curating and standardizing this dataset to follow the ETS vocabulary and FAIR principles. I wish to link the zooplankton dataset to the Open Traits Network especially to allow the use of zooplankton traits information in marine ecology research and modelling. 

I offer my expertise in numerical analysis of traits data and environmental datasets. I am very much interested in collaborations regarding the synthesis of trait information and functional ecology theory across systems and taxonomic groups. I am leading a working group in February 2023 regarding traits and ecosystem functioning which mainly utilizes our zooplankton traits dataset but I would like to introduce other datasets from the Open Traits Network for our participants to potentially utilize.

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi Patrick, welcome aboard!  Great to have more representation from the marine realm!  Your profile is now active at: https://opentraits.org/members/patrick-r-pata

**Comment by PatrickPata** [comment]
Thank you! I'm glad to be part of this. Looking forward to contributing!
