### ISSUE TITLE
remove 'posts' page

### ISSUE THREAD

**Issue by rachaelgallagher** [open-traits-network/open-traits-network.github.io#21]
I don't think we should include a Posts page on the site anymore. What do others think? @bmaitner @jhpoelen @jmadin @iimog @caterinap

**Comment by jhpoelen** [comment]
I'd rename to "news" and use to document milestones, publications and workshops.

**Comment by bmaitner** [comment]
> I'd rename to "news" and use to document milestones, publications and workshops.

+1

**Comment by rachaelgallagher** [comment]
I wonder if a lack of regular 'news' might make the OTN look a bit idle, though? DO we think there will be sufficient news to keep this looking fresh? Perhaps embedding our twitter feed on the home page would serve the same purpose?

**Comment by jhpoelen** [comment]
To me twitter is useful for things that are fleeting. The "news" or "blog" would serve more like a resume for the project. Sort of like press releases.

**Comment by rachaelgallagher** [comment]
OK - agreed, I like the idea of press releases for things that are being achieved along the way. Perhaps 'Milestones' is another way of titling this? 'News' has lots of connotations in society is all. Milestones catalogues real achievements. Maybe I am splitting hairs here though...

**Comment by jmadin** [comment]
I've changed it to News. And also added twitter link to footer.
