### ISSUE TITLE
Please add Dunn et al, 2015 to the OTN dataset registry

### ISSUE THREAD

**Issue by jhammock** [open-traits-network/open-traits-network.github.io#216]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: Dunn-et-al-2015
name: Dunn et al, 2015
contentURL: https://opendata.eol.org/dataset/7195e9d9-ad49-48f8-96df-95d2934cbf79/resource/3396fd83-87e0-4a90-8fa0-35cf5a070c55/download/dunnetal2015.zip
datasetDOI_URL: https://opendata.eol.org/dataset/dunn-et-al-2015
contactName: Jen Hammock
contactEmail: secretariat@eol.org|jen.hammock@gmail.org
license: CC0
traitList: body symmetry
higherGeography: 
decimalLatitude:
decimalLongitude:
taxon: Porifera
eventDate: 
paperDOIcitation: https://doi.org/10.1016/j.tree.2015.03.003
description: Dunn, C.W., Leys, S.P. and Haddock, S.H., 2015. The hidden biology of sponges and ctenophores. Trends in ecology & evolution, 30(5), pp.282-291. https://doi.org/10.1016/j.tree.2015.03.003
taxaList: 
usefulClasses: 
dataStandard: 
standardizationScripts: 
webpage: 
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by jhpoelen** [comment]
@jhammock I've added an entry for Dunn et al. at https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_datasets/dunn-et-al-2015.md . Please confirm by closing this issue.
