### ISSUE TITLE
I'd like to ... link from OTN member pages to their respective Scholia author profiles

### ISSUE THREAD

**Issue by Daniel-Mietchen** [open-traits-network/open-traits-network.github.io#218]
e.g. from
https://opentraits.org/members/stefanie-dekeyzer
to
https://scholia.toolforge.org/author/Q85683771 .

There are several ways to do this:
- if the OTN user page already has a Wikidata URL, then the last bit of it &mdash; ```Q85683771``` in the example above &mdash; then the corresponding Scholia author page would be located at [https://scholia.toolforge.org/**author**/```Q85683771```](https://scholia.toolforge.org/author/Q85683771)
- if there is an ORCID URL (e.g. https://orcid.org/0000-0001-9525-2742 in the example case), then the Scholia page can be reached via [https://scholia.toolforge.org/**orcid**/```0000-0001-9525-2742```](https://scholia.toolforge.org/orcid/0000-0001-9525-2742)
- if there is a GitHub ID (not given in this case but known from the [request to join](https://github.com/open-traits-network/open-traits-network.github.io/issues/210)), then the Scholia page can be reached via [https://scholia.toolforge.org/**github**/```StefanieDekeyzer```](https://scholia.toolforge.org/github/StefanieDekeyzer)

There are other ways (e.g. [https://scholia.toolforge.org/**twitter**/```irene_moon```](https://scholia.toolforge.org/twitter/irene_moon)
would works as well) but those do not have a field in the current data schema for the OTN member pages.

**Comment by jhpoelen** [comment]
@Daniel-Mietchen please re-open this issue if you feel this issue has not been addressed.
