### ISSUE TITLE
I'd like to ... become an editor

### ISSUE THREAD

**Issue by caterinap** [open-traits-network/open-traits-network.github.io#221]
Hi! 
maybe I could help with new members / datasets. Especially the ones that will be sent by email.
cheers

**Comment by jhpoelen** [comment]
you are now an OTN editor. Hurrah!

![Screenshot from 2022-08-10 17-31-15](https://user-images.githubusercontent.com/1084872/183945267-5815e7f5-5e14-483c-a1f9-137c79db246f.png)
