### ISSUE TITLE
Please add [ucimlr-anderson-1935-iris] to the OTN dataset registry

### ISSUE THREAD

**Issue by Daniel-Mietchen** [open-traits-network/open-traits-network.github.io#226]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: ucimlr-anderson-1935-iris
name: UCIMLR-Iris
contentURL: https://archive.ics.uci.edu/ml/machine-learning-databases/iris/
datasetDOI_URL: 
contactName: Daniel Mietchen
contactEmail: daniel.mietchen@ronininstitute.org
license: CC BY 4.0
traitList: sepal length in cm | sepal width in cm | petal length in cm | petal width in cm   
higherGeography: North America
decimalLatitude: 48.65806 
decimalLongitude: -65.75278
taxon: Iris
eventDate: about 1934
paperDOIcitation: https://doi.org/10.1111/j.1469-1809.1936.tb02137.x
description: Flower traits
taxaList: Iris setosa, Iris versicolor, Iris virginica
usefulClasses: 
dataStandard: Fisher 1936
standardizationScripts: 
webpage: https://archive-beta.ics.uci.edu/ml/datasets/iris
---
```
This dataset is famous enough to have Wikipedia articles about it in 12 languages as well as a range of public versions and mirror copies. Not sure how to capture that but [its Wikidata entry](https://www.wikidata.org/wiki/Q4203254) is perhaps a useful starting point.
The UCI-MLR version listed here corrects some of the statistical mistakes found in the original work by Fisher, yet it introduces a spelling error in the name of Iris versicolor.

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by BErfanian** [comment]
Hello, 
Thank you for registering the Iris dataset, 
Here is a link to the dataset:
https://opentraits.org/datasets/UCIMLR-Iris
