### ISSUE TITLE
I'd like to ... report missing data for dataset Bland_2017

### ISSUE THREAD

**Issue by chiras** [open-traits-network/open-traits-network.github.io#227]
Hey, 

I was not able to find the actual data for Bland_2017.

The URLs both point to the original article, the Supplement does not contain data. The article is behind a paywall, thus whether the link to actual data is in there somewhere, I can not verify. 

Thanks, 
Alex

**Comment by BErfanian** [comment]
Hi Alex @chiras
Have you checked this?
contentURL: https://raw.githubusercontent.com/LucieBland/Crayfish-extinction-risk/master/Crayfish_Species_Dataset.csv

**Comment by chiras** [comment]
Thanks! 
@bmaitner has updated it in the meantime to have the correct URL included. Thanks Brian!
https://github.com/open-traits-network/open-traits-network.github.io/commit/93fe2d6d3776f3f093a7b0e37376620d2088e6b0
