### ISSUE TITLE
AusTraits

### ISSUE THREAD

**Issue by ehwenk** [open-traits-network/open-traits-network.github.io#229]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: austraits
name: AusTraits
contentURL: https://zenodo.org/record/5112001/files/austraits-3.0.2.rds
datasetDOI_URL: https://zenodo.org/record/5112001
contactName: Elizabeth Wenk
contactEmail: ehwenk@gmail.com
license: CC BY
traitList: 462 plant traits, with definitions at http://traitecoevo.github.io/austraits.build/articles/Trait_definitions.html
higherGeography: Australia
decimalLatitude:
decimalLongitude:
taxon: Tracheophyta
eventDate: about 1900 to current
paperDOIcitation: doi.org/10.1038/s41597-021-01006-6
description: AusTraits is an open-source, harmonized database of Australian plant trait data.
taxaList: 28640 taxa, mostly aligned with the Australian Plant Census (APC)
usefulClasses: Mostly in-situ measurements on plant individuals
dataStandard: Taxonomy standardized to the Australian Plant Census (APC). Plant trait definitions and allowable values documented in our trait definitions file.
standardizationScripts: https://github.com/traitecoevo/austraits.build
webpage: https://austraits.org
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by bmaitner** [comment]
Thanks for registering this!  The AusTraits registry is now live at: https://opentraits.org/datasets/austraits

**Comment by bmaitner** [comment]
Also tweeted about it for good measure :)

**Comment by jhpoelen** [comment]
@bmaitner nice! can you share tweet url and screenshot in this issue?

**Comment by bmaitner** [comment]
@jhpoelen Great idea!

https://twitter.com/Open_Traits/status/1559559219401162752?s=20&t=g2Z2kM8PBnl2PMx5E2vbWA

![image](https://user-images.githubusercontent.com/11130881/184923682-9f5ccfe0-9706-481d-8e68-2c735f3d3e95.png)

**Comment by ehwenk** [comment]
Thank you! Looking forward to the upcoming meeting.
