### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by jessRmarsh** [open-traits-network/open-traits-network.github.io#235]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: jess_marsh
name: Jess R Marsh
email: jessmarsh@invertsau.org
homepage: http://example.org
lat: -35.7818 
long: 137.7613
affiliation: Invertebrates Australia, Ltd. Harry Butler Institute, Murdoch University
github: jessRmarsh
orcid: https://orcid.org/0000-0002-4062-4155
wikidata: 
scholia:
---

Jess is an invertebrate ecologist and taxonomist based in South Australia

## Collaboration statement
My work is focused around invertebrates and I am interested in the use of traits, ecological, and spatial data to investigate some of the (many) questions and challenges facing invertebrate conservation in Australia and internationally. I am particularly interested in inter-taxa interactions and dependencies, and the influence that this has on species conservation. I am also a taxonomist, working on spiders. 

I lead the AusInverTraits project - using the AusTraits framework and workflows to create an integrated traits database for invertebrate species in Australia. 

I am keen to collaborate and can provide invertebrate taxonomic and ecological expertise. 


```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hey @jessRmarsh - thanks for registering and welcome to OTN! Hoping to learn more about AusInverTraits and discover how your activities are related to other OTN members. 

If all goes well, your OTN member profile should be available at https://opentraits.org/members/jess-marsh in a couple of minutes. Please let me know if you have any questions / comments.
