### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by felixpleiva** [open-traits-network/open-traits-network.github.io#239]
---
layout: member
id: felixpleiva
name: Félix P Leiva
email: felixpleiva@gmail.com
homepage: https://github.com/felixpleiva
lat: 51.82
long: 5.87
affiliation: Department of Animal Ecology and Physiology, Radboud University, the Netherlands 
github: felixpleiva
orcid: 
wikidata: 
scholia: 
---

Félix is an animal eco-physiologist in Nijmegen, the Netherlands. 

## Collaboration statement
I am an eco-physiologist interested in understanding how terrestrial and aquatic ectotherms respond to increasing temperature, low oxygen levels, and salinity changes, among other environmental perturbations. To do so, I am using experimental and comparative approaches that allow testing the generality of various hypotheses in physiology, ecology and evolution. Next year I will start my postdoctoral project, **MetaR**, funded by the [Alexander von Humboldt-Stiftung](https://www.humboldt-foundation.de/en/). In this project, I will assemble and curate a large, intra-and-interspecific database on metabolic rates of ectotherms (invertebrates, fish, amphibians and reptiles), globally distributed across realms (marine, freshwater, intertidal and terrestrial), climate zones (polar, temperature and tropical), and from the deepest ocean to the highest mountains, aiming to synthesise the impact of global environmental change on a key physiological trait in ectotherms: their metabolic rate. 

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by BErfanian** [comment]
Dear Félix, 
Welcome to OTN. Here is a link to your profile: 
https://opentraits.org/members/felixpleiva
