### ISSUE TITLE
I'd like to ... think how to make the 10 rules alive

### ISSUE THREAD

**Issue by caterinap** [open-traits-network/open-traits-network.github.io#242]
Hi! 

How to encourage the scientific community (and ourselves) to update the 10 rules when new tools / field practices appear?

The idea would be to write in the paper something like that "We encourage the scientific community to update these rules when new tools and practices emerge. This is possible at the following web page: http://opentraits.org/lifecycle.html"

But then what should we put on the webpage? The full paper? Rule titles and subtitles + bullet points?

Any ideas are welcome!

**Comment by bmaitner** [comment]
I think this is a great idea.  If the licensing permits it, I'd vote for including the full paper.  That way all the text is there to edit and update as new best practices emerge.  The other kind of nice thing here is that the full rationale for our updates and changes will be preserved in the comments and pull requests.

**Comment by jhpoelen** [comment]
@caterinap @bmaitner I am also in favor of putting all the rules up there and turn the paper into a living document. 

Perhaps we can update the name of the page to be more descriptive . . . like "best practices" or "publishing traits" or "how-to" . 

Curious to hear thoughts.

**Comment by caterinap** [comment]
@jhpoelen, a more descriptive title is good idea. I like "best practices" because it captures better the whole cycle ("how-to" is maybe too generic). 
Including the full paper would be the easiest. I am sure what we will be allowed to do and if we can choose which CC license we want ([MEE website](https://besjournals.onlinelibrary.wiley.com/hub/journal/2041210X/about/open-access), [Wiley policy](https://authorservices.wiley.com/asset/At-a-Glance-Creative-Commons-License-Guide-PDF.pdf)). There is also maybe a 12 months embargo before putting the accepted version online. Maybe we can ask the editor directly.

**Comment by bmaitner** [comment]
@caterinap , good idea, I think asking the editor is probably the best option. If there is an embargo on the accepted version, presumably in the interim we can post the preprint version (and maybe include a link to the accepted version?)

**Comment by jhpoelen** [comment]
ok, so rename page to "best practices" and shove the pre-print on there in markdown ?

**Comment by bmaitner** [comment]
@jhpoelen that sounds good to me

**Comment by jhpoelen** [comment]
@caterinap or others - do you agree?

**Comment by jmadin** [comment]
I think it’s a great idea.

**Comment by jhpoelen** [comment]
I took the liberty to rename the lifecycle page to best practices as suggested. 

![image](https://user-images.githubusercontent.com/1084872/194397191-2ffc2ef9-9ea7-4f9e-921c-a235aabaad79.png)

Can someone else copy / paste the article into the best-practices.md file? 

https://github.com/open-traits-network/open-traits-network.github.io/edit/master/best-practices.md

Thanks!

**Comment by caterinap** [comment]
I also agree! I asked the original Word file to Alex so we can copy it in the best-practices.md file. I tried to extract the text from the PDF but it was a mess with line numbers and hard returns.

**Comment by chiras** [comment]
Work in progress: https://github.com/open-traits-network/open-traits-network.github.io/tree/best-practices
