### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by faosilveira** [open-traits-network/open-traits-network.github.io#243]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: fernando-a-o-silveira
name: Fernando AO Silveira
email: faosilveira@gmail.com
homepage: leept.webnode.com
lat: 19.8707° S
long: 43.9677° W
affiliation: Department of Genetics, Ecology and Evolution, Federal University of Minas Gerais, Brazil
github: faosilveira
orcid: https://orcid.org/0000-0001-9700-7521
wikidata: https://www.wikidata.org/wiki/Q62558788
scholia: https://scholia.toolforge.org/author/Q62558788 # for more information about scholia see https://scholia.toolforge.org . 
---

Fernando is a plant ecologist based in Belo Horizonte, Brazil. 

## Collaboration statement
My primary research interests are on the ecology and evolution of seed traits, and how we can improve seed-based techniques to manage and restore tropical grassy biomes. 

My collaborators, students and I have been working on theoretical and empirical studies that can advance our understanding of the regeneration niche by creating and analyzing databases on plant reproductive traits (flowers, fruits and seeds). 
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by BErfanian** [comment]
Dear Fernando, 
Here is a link to your profile:
https://opentraits.org/members/fernando-a-o-silveira
The [Wikidata](https://www.wikidata.org/wiki/Q62558788) and [Scholia](https://scholia.toolforge.org/author/Q62558788) profiles are not yours. Would you please edit the links?
All the best,
Bagher
