### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by rajivrsgis** [open-traits-network/open-traits-network.github.io#257]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: rachael-v-gallagher
name: Rachael V Gallagher
email: rachael.gallagher@mq.edu.au
homepage: http://example.org
lat: -33.77403
long: 151.115978
affiliation: Department of Biological Sciences, Macquarie University, Sydney, NSW, Australia 
github: rachaelgallagher
orcid: https://orcid.org/0000-0002-4680-8115
wikidata: https://www.wikidata.org/wiki/Q62558788
scholia: https://scholia.toolforge.org/author/Q62558788 # for more information about scholia see https://scholia.toolforge.org . 
---

Rachael is a plant ecologist based in Sydney Australia. 

## Collaboration statement
I enjoy working on applied problems in plant conservation using spatial analyses and traits. My primary (soon to be) open trait dataset is AusTraits - a curated dataset on the traits of Australian plants. This resource was created with harmonisation pipeline created by my collaborator Daniel Falster.

I can offer expertise in workflows for cleaning occurrence data and combining with trait data. I am also happy to help connect people together around traits by running working groups, hosting visitors in my lab, organising symposia at conferences and maintaining our Open Traits website.


```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by BErfanian** [comment]
Hi and thank you for registering one of our editors :)
https://opentraits.org/members/rachael-v-gallagher

**Comment by jhpoelen** [comment]
@rajivrsgis If you'd like to register as an OTN member, please fill-out the member form with your information.

Like @BErfanian noted, it appears that you submitted the default values for the form, those of @rachaelgallagher , a founding member of the OTN . . . 

Please holler if you need help getting registered.

**Comment by jhpoelen** [comment]
Closing stale issue @rajivrsgis - please re-open issue and fill out the member registration form if you are still interested to join.
