### ISSUE TITLE
Please add [Rasgos-CL] to the OTN dataset registry

### ISSUE THREAD

**Issue by dylancraven** [open-traits-network/open-traits-network.github.io#262]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: rasgos-cl
name: Rasgos-CL
contentURL: https://github.com/dylancraven/Rasgos-CL/tree/main/Data # direct data download, NA when not available
datasetDOI_URL: https://github.com/dylancraven/Rasgos-CL # points to human readable landing page
contactName: Dylan Craven
contactEmail: dylan.craven@umayor.cl
license: CC BY 2.0
traitList: 23 plant traits
higherGeography: Chile
decimalLatitude:
decimalLongitude:
taxon: Tracheophyta
eventDate: 1833 to current
paperDOIcitation: 10.1111/geb.13755
description: A database of functional traits for woody species in Chile
taxaList: 662 plant taxa, standardized with the World Checklist of Vascular Plants and TROPICOS
usefulClasses: Mostly aggregated traits compiled from literature in Spanish
dataStandard: Standardization of traits mainly following GIFT (Weigelt et al. 2020)
standardizationScripts: NA
webpage: NA
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hi @dylancraven thanks for your request to register your dataset in the Open Traits Network.

As I was reviewing your datasets, I was wondering: Are you aware of the best practices published by OTN members? Please see https://opentraits.org/best-practices . If not, I'd be curious to hear your thoughts on the "Ten (mostly) simple rules".

For instance, in https://opentraits.org/best-practices/05_structure-trait-data#apply-version-control , the following is mentioned

> "Use of versioning or change control systems like Git (Spinellis, 2012) is highly recommended to keep track of changes to data. Also, conventions that include a current (e.g., my_data_current.tsv) and versioned copy (e.g. my_data_1.0.tsv) help automated systems by providing a stable interface for indexing."

Did you consider adding such a "current" version file?

**Comment by dylancraven** [comment]
hi @jhpoelen, we tried to mostly follow the guidelines mentioned in the article, although I don't think we were aware of the article when we wrote the manuscript. In the GitHub repository, we have included the aggregated trait data (average values per species), plus the original data ( "RasgosCL_longformat_Version1.csv") and the corresponding sources ("RasgosCL_References.csv"). Regarding versioning, we have indicated in the name of both trait data files the version (i.e. "_Version1", and have also indicated that this version is the first and current version of the data in the information about the Release (v. 1.0.0). In this regard, we tried to follow other data bases such as TRY and GIFT that assign successive numbers to each version, i.e. 1, 2, and 3. Does this answer your question?

**Comment by jhpoelen** [comment]
@dylancraven thanks for taking the time to reply. 

I noticed you chose to encode the version of a file in their filename. Note that Git already offers versioning as well as release mechanism, so adding a versioning mechanism in the filename is technically superfluous. 

This is why I am curious to hear your ideas on my following questions:

1. If you choose to keep Have you considered adding a second set of "current" files e.g., `RasgosCL_longformat_current.csv` in addition to `RasgosCL_longformat_Version1.csv` ? Having a stable path (or URL) to your data would "help automated systems by providing a stable interface for indexing." 

2. If you are willing to reply on GitHub for versioning (as many / most do), I'd suggest to strip the version number altogether and rename files like `RasgosCL_longformat_Version1.csv` to `RasgosCL_longformat.csv`. Reasoning similar to the one given in 1.

If you keep the naming convention as is, folks would have to manually update their scripts / infrastructures to reuse your data each time you publish a new version.

**Comment by dylancraven** [comment]
Thanks for the explanation, it makes a lot of sense. I think we will probably go with option 2.

**Comment by jhpoelen** [comment]
@dylancraven thanks for engaging in conversation and having a peek at the best practice page. Curious to hear how your rich trait dataset will end up being used! 

You dataset should be visible on https://opentraits.org/datasets/rasgos-cl and https://opentraits.org/datasets shortly.
