### ISSUE TITLE
add OTN member profiles and map

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#3]
as suggested by @iimog -

```
use something similar to this: https://www.de-rse.org/en/map.html which
is fed by a simple js file:
https://github.com/DE-RSE/www/blob/gh-pages/_includes/mapdata.js
including name, image, testimonial, ...
```

**Comment by jhpoelen** [comment]
Also, @caterinap mentioned to use existing google spreadsheet to populate profiles from co-author list.

**Comment by iimog** [comment]
I have a working version of the map in a local clone. It is not populated with the OTN members, yet and the design needs a little polishing. I guess adding the authors from the spreadsheet is easier than having everyone add themselves but it is probably quite some manual work as the locations have to be mapped to coordinates. I'll let you know as soon as I have something you can look at.

**Comment by rachaelgallagher** [comment]
Great - thanks Markus. I can probably find someone to extract the coordinates for you if that would be helpful?


Dr Rachael Gallagher

Australian Research Council DECRA Fellow


Room E8B 317

Department of Biological Sciences

Macquarie University

North Ryde

NSW 2109


Ph: 9850 8404


Plants = Life

________________________________

**Comment by rachaelgallagher** [comment]
@silviapine is going to compile the lat-long coordinates for us Markus. Thanks Silvia!

**Comment by silviapine** [comment]
Happy to help! 😀

-
S.

**Comment by iimog** [comment]
In my fork I populated the [`_members`](https://github.com/iimog/open-traits-network.github.io/tree/master/_members) with the authors of the OTN manuscript thanks to the help of @silviapine. I extracted name, affiliation, longitute and latitute (only the first affiliation and coordinates for each author). I also used this information to populate the [OTN member map prototype](http://markus.ankenbrand.me/open-traits-network.github.io/map). As a show-case I also populated the fields: image, homepage and info which is also used in the OTN map (you can find my pin in Würzburg, Germany). Let me know what you think. I can create a pr anytime. The map uses [leaflet.js](https://leafletjs.com/) to work (currently copied to the repo but we can use a CDN instead).

**Comment by iimog** [comment]
I'm happy that you like it so far. I continued a little bit:
 - I fixed the special character problem for `Hervé` (a typo: `&eaccute;` -> `&eacute;`)
 - I use profile pictures from github if no picture is provided but the github account name is (I added this info for all participants in this issue). It loads a little slower but it works.
 - I also added preliminary documentation to the `README` file. All information for the map is extracted from the `yml` header in the `_members` files. I introduced some fields that I thought useful but we can add others without problem (also without breaking anything).
 - I can easily create a table view from the `_members` files as well, we only need to decide what info to show and design things (like where that table should be located and how it should look like). And also if it should have additional functionality like zooming to the pin of the person when clicked in the table.
 - I really like the suggestion to filter the map by taxonomic expertise and I have an idea on how to implement it. But I think we need to discuss how we want to handle this information in general: does every member need to add a taxonomic expertise, do we restrict it to predefined values, can members be experts in multiple groups, etc. If we decide on exactly one group out of a predefined set for every member we could also use distinct pins with specific icons in addition to the filtering.

I'll open a pull request with my work so far to make it easier for others to see what I did and to add to it.

**Comment by jhpoelen** [comment]
@iimog Nice - thanks for taking the first stab at this! I took the liberty to merge to pull requests so that others can more easily enjoy your work at https://opentraits.org/members and https://opentraits.org/map . Am closing this issue and suggest to open individual issues to improvements on the member list and member map.
