### ISSUE TITLE
margins too wide on the style sheet for main pages

### ISSUE THREAD

**Issue by rachaelgallagher** [open-traits-network/open-traits-network.github.io#32]
@jmadin can we widen the margins a little to make the text easier to see? Thanks

**Comment by jmadin** [comment]
@rachaelgallagher Hi Rach. I'll take a look!  (You mean *reduce* the margins / increase middle text area, right?)

**Comment by rachaelgallagher** [comment]
@jmadin Hey Josh! Yes please, that's what I meant. things look a bit squashed at the moment

**Comment by jhpoelen** [comment]
Thanks @jmadin for increasing the middle text area.
