### ISSUE TITLE
add "edit" button to each page

### ISSUE THREAD

**Issue by jhpoelen** [open-traits-network/open-traits-network.github.io#34]
Currently, the member profiles have an "edit" link to help facilitate update a profile.

Suggest to add an "edit" button for each opentrait website page to make it easier to update / add content.

**Comment by rachaelgallagher** [comment]
The Resources page could really benefit from this addition - people can then propose new protocols etc. which can be reviewed by the OTN community before being included.

**Comment by bmaitner** [comment]
Agreed, having a clear "edit" link shows that we want this to be a community-curated resource

**Comment by jhpoelen** [comment]
Added edit links to individual dataset, member pages as well as index, resources, datasets, and members pages. No styling applied, so could be prettified. Note that the page id is used in combination with a file naming convention: ```[page.id].md```.
