### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by audhalbritter** [open-traits-network/open-traits-network.github.io#36]
Hi,

I just had a look at the website. In the resource section there are links to protocols and handbooks. The handbook for modular traits is linked twice. And it might be useful to use a more descriptive name. E.g. instead of plants -> leaf functional trait handbook, handbook for modular traits etc.

Best,
Aud

**Comment by jhpoelen** [comment]
Hi @audhalbritter -

Thanks for your suggestion. 

Please update the resources page by going to:

 https://github.com/open-traits-network/open-traits-network.github.io/edit/master/resources.md 

and edit the page directly.

If you don't feel comfortable editing the page, please see https://help.github.com/en/articles/editing-files-in-your-repository or holler in this issue.

**Comment by rachaelgallagher** [comment]
Hi @audhalbritter @jhpoelen - yes! it would be great to have you do the editing directly Aud. we're here to help if you're unsure about anything

**Comment by jhpoelen** [comment]
fixed by https://github.com/open-traits-network/open-traits-network.github.io/issues/36
