### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by PaulESantos** [open-traits-network/open-traits-network.github.io#55]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: paul-e-santos-andrade
name: Paul Efren Santos Andrade
email: paulefrens@gmail.com
homepage: https://paulefrensa.rbind.io
lat: -13.521735
long: -71.959390
affiliation: Universidad Nacional de San Antonio Abad del Cusco  
github: PaulESantos
---

I'm a plant ecologist based in Cusco - Peru. 

## Collaboration statement
I'm working with plant traits along high altitude grassland in Peru. 

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
I've just added [your profile.](https://github.com/open-traits-network/open-traits-network.github.io/blob/master/_members/paul-e-santos-andrade.md)  You now show up on the members page and on the map.  Thanks for being the first user to try out our new registry system!  And for being our point in South America :)

**Comment by rachaelgallagher** [comment]
Welcome Paul! I'm so pleased to have our first new member on the site!
