### ISSUE TITLE
Consider making tweetable videos showing how to join, add content, etc.

### ISSUE THREAD

**Issue by bmaitner** [open-traits-network/open-traits-network.github.io#58]
A lab mate suggested that we consider making short, tweetable videos showing how to join, add content, etc.  Does this seem like it would be generally useful?

**Comment by jhpoelen** [comment]
+1

**Comment by rachaelgallagher** [comment]
Top idea! How can we make it happen? What are you thinking here @bmaitner

**Comment by bmaitner** [comment]
I think we just need to enlist the help of someone with some video skills.  @audhalbritter has put together some excellent tutorial videos for trait pipelines in the past, I think she might have some good ideas!  I think this could be very simple, perhaps just screen capture of someone going through the processs, perhaps with a voiceover explaining they're doing?

**Comment by rachaelgallagher** [comment]
OK - that sounds good. @audhalbritter do you have any ideas/tips?

**Comment by audhalbritter** [comment]
Yes, that sounds like a great idea! I'm thinking of something like this: https://www.youtube.com/watch?v=Bhq_MbSwa-A&t=38s
But it would show a screen and somebody clicking through the process. And pop-up text explaining different steps. Which processes do you want a video for? Can you make a list? Then I can make video for one of them...

**Comment by audhalbritter** [comment]
Ok, I see. I think it should then be a combination of watching a person doing things and a close up from the screen to show the steps on the computer. For example, a person wants to register as a member. First you see the person, then some steps are shown where you only see the screen. Then you see the editor (= another person), who is reviewing and accepting. Then they shake hands and the editor welcomes the new member.
An alternative of having people would be to have simple drawings to make it a bit more interesting. I don't know how you would do this, but I can probably figure it out.

**Comment by audhalbritter** [comment]
Hi again, I just registered a fake person and recorded it. It works well and I can combine it with some shots from a real in front of a computer. Can I get admin/review rights just for these videos, otherwise one of you has to record the reviewing process.

And just delete whatever fake people and data I send...

**Comment by jhpoelen** [comment]
@audhalbritter Harry Potter isn't real? ; ) I'll hand you the keys to the kingdom in a minute.

**Comment by jhpoelen** [comment]
@audhalbritter please confirm you have access . . .

**Comment by audhalbritter** [comment]
Of course her is real, but not everybody knows that!
I'm not sure how to check if I have more rights now...

**Comment by audhalbritter** [comment]
Ah, now I got a confirmation by email... I think it works

**Comment by rachaelgallagher** [comment]
Thanks @audhalbritter there are so many strings to your bow... Harry Potter aficionado, web video star, trait wizard.... obs studio is great @jhpoelen - you are full of great advice!

**Comment by bmaitner** [comment]
> Thanks @audhalbritter there are so many strings to your bow... Harry Potter aficionado, web video star, trait wizard.... obs studio is great @jhpoelen - you are full of great advice!

+1 to both of those statements

**Comment by audhalbritter** [comment]
Haha, thanks a lot! Will work on some videos this week and send them to you...

**Comment by audhalbritter** [comment]
Does anybody of you @rachaelgallagher @bmaitner @jhpoelen have the opentrait logo in good quality?

**Comment by bmaitner** [comment]
@phylosaurus ?

The only logo I have floating around is the [this one](https://github.com/open-traits-network/open-traits-network.github.io/blob/master/images/logo.jpg)

**Comment by audhalbritter** [comment]
Thanks!

**Comment by phylosaurus** [comment]
@audhalbritter @bmaitner 
Here you go! SVG file.
[logo1.zip](https://github.com/open-traits-network/open-traits-network.github.io/files/3732380/logo1.zip)

**Comment by audhalbritter** [comment]
Thanks @phylosaurus!

**Comment by audhalbritter** [comment]
What do you think about this? @bmaitner @jhpoelen @rachaelgallagher 
https://www.youtube.com/watch?v=9icvsYNBzrE&feature=youtu.be

**Comment by bmaitner** [comment]
Looks good to me!  If everyone else is happy, I can tweet this out!

**Comment by jhpoelen** [comment]
@audhalbritter Just tried to have a look and youtube said: "this video has been removed by the user".

**Comment by rachaelgallagher** [comment]
I can see it @jhpoelen. Looks great @audhalbritter! Only issue is that you can also register via a link at the 'Members' tab. Does anyone think we need to acknowledge this?

**Comment by jhpoelen** [comment]
Was able to watch the video now. Pretty cool! Big fan of kermit. What is he up to these days? 

Hmm. We should probably update our landing/about page to point folks to the "contact" or "member" pages. The current (outdated) link to the _members/README.md is for editors that handle the OTN member / dataset registrations. 

@audhalbritter would it be tricky to update video to include something like:

search -> opentraits.org -> member page -> click on "introduce yourself" -> register new member issue ? 

If it's too time consuming I am ok to leave as is.

**Comment by audhalbritter** [comment]
Ok, that's not a big change. I'll try to do it tonight.

**Comment by audhalbritter** [comment]
New version here:
https://www.youtube.com/watch?v=bgVd-OHdZH4&feature=youtu.be

Is it ok to host them on my youtube channel? Or do you want a video file, or should we make an open trait youtube channel?

If you like the style of the video I can make the other tutorials as well. And if you have better ideas for music, let me know. The music is horrible, but it needs to be free and I did not want to spend hours searching for music :-)

**Comment by bmaitner** [comment]
Actually, maybe making an Open Traits youtube channel wouldn't be a bad idea.  Then we could feature tutorials, lectures, etc.

**Comment by jhpoelen** [comment]
@audhalbritter nice - thanks for making that update! I am glad Kermit still made the cut! 

As far as channel goes: I can go either way. We can always move / re-organize videos around later if needed.

**Comment by rachaelgallagher** [comment]
Thanks so much Aud these are great and feel free to make others. I agree we can just keep them on your channel for now. Kermit - what a guy!

Dr Rachael Gallagher

ARC DECRA Fellow
Deputy Chair, NSW Threatened Species Scientific Committee

Macquarie University
Department of Biological Sciences


Plants = Life

________________________________

**Comment by bmaitner** [comment]
I've tweeted out a link to your video, @audhalbritter !  Perhaps one showing how to add datasets would also be useful?

**Comment by audhalbritter** [comment]
Ok, I'll try to make the other videos over the next couple of days...

**Comment by audhalbritter** [comment]
Hi again,
I've been a bit busy, so was not able to make more videos... I've now made an issue with a new data set. What would be the next steps that you want to see in the video?
Response from sb from the OpenTraits saying thanks, and what happens then?

**Comment by jhpoelen** [comment]
How about . . . 

1. go to datasets page 
2. search (ctrl-F) for dragons
3. select dataset page
4. go to dataset url / download data

**Comment by audhalbritter** [comment]
That sounds good for downloading data. And you mean the data set page on the opentrait webpage, right?

Maitner suggested also to make a video about how to add a data set. So what happens after somebody wants to add a data set and opens an issue and describes the data. Do you check it and then accept it? And how is the data added? Should I also show that?

**Comment by jhpoelen** [comment]
@audhalbritter apologies for delayed reply. 

> That sounds good for downloading data. And you mean the data set page on the opentrait webpage, right?

yep!

> Maitner suggested also to make a video about how to add a data set. So what happens after somebody wants to add a data set and opens an issue and describes the data. Do you check it and then accept it? And how is the data added? Should I also show that?

I thought your start was excellent. The steps I suggested were to complete the cycle.

So, in summary something like: first register dataset by author,  then review dataset by editor, then use dataset by collaborator. Hope this is inspiring, am curious what you make of it.

**Comment by audhalbritter** [comment]
Ok, I'm working on this now. The first part is done. But how do I accept a new data set, or how does the dragon data set get's on the open trait data set page? I closed the issue, but this did not do the trick. Do I have to accept it?

**Comment by jhpoelen** [comment]
@audhalbritter great to hear that you are making progress. To make the dataset appear on opentraits.org, you'll have to add a file to the _dataset/ directory with the dataset template it. For instructions, see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme .

**Comment by audhalbritter** [comment]
@jhpoelen @bmaitner @rachaelgallagher here is the next video on how to submit a dataset. 
Should I change to:
OTN editor reviews, asking for info if needed.
On approval, OTN editor creates a new dataset file

Anything you want differently?

https://www.youtube.com/watch?v=d6XLmQizY0g&feature=youtu.be

**Comment by phylosaurus** [comment]
Cool! Very minor quibble, but if it's not too much trouble, could we use
the vector graphic of the logo I sent out? The white background of the logo
is a bit noticable on black. No worries if this is too bothersome.

Best,

Dan

**Comment by jhpoelen** [comment]
@audhalbritter just watched it . . . looks great! thanks for creating the video.

**Comment by audhalbritter** [comment]
No problem @phylosaurus I can use the one you sent earlier.

**Comment by rachaelgallagher** [comment]
Fantastic video! @audhalbritter Thanks so much. Sorry for the slow reply - I've been out in the field these last few weeks

**Comment by audhalbritter** [comment]
Updated video:
https://www.youtube.com/watch?v=PtvIf3OnXRc

**Comment by jhpoelen** [comment]
Thanks to @audhalbritter for creating the videos on how to register members and datasets with the OTN.
