### ISSUE TITLE
Please add TetraDENSITY to the OTN dataset registry

### ISSUE THREAD

**Issue by LucaSantiniEco** [open-traits-network/open-traits-network.github.io#61]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: TDens
name: TetraDENSITY
datasetDOI_URL: https://figshare.com/articles/TetraDENSITY_Population_Density_dataset/5371633
contactName: Luca Santini
contactEmail: luca.santini.eco@gmail.com
license: CC BY
traitList: >18,000 georeferenced and dated population density estimates in terrestrial vertebrates
decimalLatitude: Yes
decimalLongitude: Yes
taxon: Tetrapodes (Amphibians, Reptiles, Birds, Mammals)
eventDate: 1926 to present
paperDOIcitation: https://doi.org/10.1111/geb.12756
description: The dataset includes taxonomic information on species, population density estimate, year of data collection, season, coordinates of the locality, locality name, habitat, sampling method and sampling area.
taxaList: 79 sp. of Amphibians, 284 sp. Reptiles, 1174 sp. of Birds, 564 sp. of Mammals
usefulClasses: Individual population estimates
webpage presenting the latest version: https://lucasantini.com/tetradensity-database/
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by rachaelgallagher** [comment]
Hi @LucaSantiniEco Thanks for registering your dataset with Open Traits! I have approved it and it will soon appear online - it looks like a great resource. If you haven't joined the Open Traits Network (OTN) as a member I'd like to encourage you to do that as well. Joining the OTN increases your visibility to others interested in hour expertise and datasets.

**Comment by rachaelgallagher** [comment]
@jhpoelen This is my first duty as editor - can you please let me know if I've missed something? Thanks!

**Comment by jhpoelen** [comment]
@rachaelgallagher sure! I added some comments. Also, if you mention the issue # in the commit comment title, the commit will be linked to the issue. This makes for an easier review.

**Comment by jhpoelen** [comment]
@rachaelgallagher nice job btw!

**Comment by rachaelgallagher** [comment]
Thanks! Missed your comment about the commit comment title...next time....

**Comment by jhpoelen** [comment]
@rachaelgallagher would you mind adding the comment instructions to registration templates footers at https://github.com/open-traits-network/open-traits-network.github.io/tree/master/.github/ISSUE_TEMPLATE ? This way, our futures selves would be reminded about this neat feature.

**Comment by rachaelgallagher** [comment]
Do you mean adding .yaml compliant field for webpage @jhpoelen? If so, done...if not please elaborate a little.

**Comment by jhpoelen** [comment]
Thanks for adding the webpage field to the template. I initially suggested to add some instructions to the templates reminding the editors to add the ```related to #[issue number]``` to the commit message when registering members/datasets.

**Comment by rachaelgallagher** [comment]
Sure thing @jhpoelen I will hopefully do this today (definitely tomorrow)
