### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by LucaSantiniEco** [open-traits-network/open-traits-network.github.io#62]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: lsantini
name: Luca Santini
email: luca.santini.eco@gmail.com
homepage: https://lucasantini.com
lat: 41.899
long: 12.514
affiliation: Institute of Research on Terrestrial Ecosystems, IRET-CNR, Viale dell’Università 32, 00185, Rome, Italy
---

Luca is a researcher in conservation biogeography and macroecology based in Rome, Italy. 

## Collaboration statement
Most of my research is at the interface between macroecology, biogeography, conservation biology and global change biology. My research relies heavily on biodiversity and trait databases, and I produced one myself (TetraDENSITY) that collates population density estimates for terrestrial vertebrates worldwide. 
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi Luca, and welcome aboard!  I've added your profile (luca-santini.md), but note that I modified the id you listed here to "luca-santini" for consistency with the other member ids.  Your profile is now visible on opentraits.org.  Additionally, thanks for submitting TetraDENSITY to the datasets!
