### ISSUE TITLE
Please add [name] to the OTN dataset registry

### ISSUE THREAD

**Issue by mrke** [open-traits-network/open-traits-network.github.io#81]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: AmP
name: AmP
datasetDOI_URL: https://www.bio.vu.nl/thb/deb/deblab/add_my_pet/
contactName: Bas Kooijman
contactEmail: salm.kooijman@gmail.com
license: CC BY
traitList: 272 trait observations of metabolic (including life history) traits for parameter estimates under the Dynamic Energy Budget theory framework
higherGeography: Global | Africa | Antarctica | Asia | Europe | North America | Oceania | South America
decimalLatitude:
decimalLongitude:
taxon: Animalia
eventDate: about 1900 to current
paperDOIcitation: 10.1371/journal.pcbi.1006100
description: A database of metabolic traits and associated parameter estimates for the Dynamic Energy Budget theory.
taxaList: 2026 animal taxa
usefulClasses: Mostly data relating to lengths and weights, development and reproduction rates (life history data) and mass exchanges (e.g. respiration rates, food consumption, etc.).
dataStandard: Standardization of traits according to http://www.debtheory.org/wiki/index.php?title=Data_types; standardization of taxonomy based on Catalog of Life,
the Encyclopedia of Life and Wikipedia
standardizationScripts: 
webpage: https://www.bio.vu.nl/thb/deb/deblab/add_my_pet/index.html
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by rachaelgallagher** [comment]
@mrke Thanks for registering your data Mike - I have approved the submission now and it should shortly appear on the site. If you've any feedback about this process, or know of others who hold data that can be added here please send them a link to the OTN homepage. we also have some instructional videos about how to register which you can tweet out or pass on https://youtu.be/bgVd-OHdZH4
