### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by EveliinaP** [open-traits-network/open-traits-network.github.io#82]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: eveliina-p-kallioniemi
name: Eveliina P Kallioniemi
email: eveliina.p.kallioniemi@artsdatabanken.no
homepage: 
lat: 
long:
affiliation: Norwegian Biodiversity Information Centre  
github: 
---

Ecologist based in Norway. Coordinating national Trait Bank database for Norwegian species and nature types. 

---

**Comment by bmaitner** [comment]
Hi Eveliina, thanks for joining!  I've added your member file and you're now visible on the OpenTraits.org member page!  Welcome!
