### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by Jhonatan-Sallo** [open-traits-network/open-traits-network.github.io#84]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: Jhonatan
name: Jhonatan Sallo-Bravo
email: sallobravo@gmail.com
homepage: 
lat: -13.530337
long: -71.950885
affiliation: Universidad Nacional De San Antonio Abad Del Cusco 
github: Jhonatan-Sallo
---

Jhonatan is a plant ecologist. 

```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi Jhonatan, I've added your profile and it is now visible on opentraits.org.  Welcome aboard!
