### ISSUE TITLE
Panama Secondary Forest Leaf Traits

### ISSUE THREAD

**Issue by dylancraven** [open-traits-network/open-traits-network.github.io#89]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: dataset
id: craven_aguasalud
name: Panama_SecondFor_LeafTraits
datasetDOI_URL: https://doi.org/10.6084/m9.figshare.1402253
contactName: Dylan Craven
contactEmail: dylan.craven@aya.yale.edu
license: CC BY 4.0
traitList: 17 leaf traits, standardized according to http://top-thesaurus.org
higherGeography: Central America
decimalLatitude: 9.216667
decimalLongitude:-79.783333
taxon: Tracheophyta
eventDate: 2010
paperDOIcitation: https://doi.org/10.1111/jvs.12632
description: A database of 17 leaf traits measured on 55 woody species and up to 1750 individuals (per species) in tropical secondary forests in Central Panama.
taxaList: 55 plant taxa, standardized using The Plant List
usefulClasses: In-situ measurements on plant individuals, averaged across species
dataStandard: Standardization of traits according to http://top-thesaurus.org/; standardization of taxonomy mainly based on http://www.theplantlist.org/
standardizationScripts: 
webpage: 
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by rachaelgallagher** [comment]
hi @dylancraven - thanks for registering this really nice dataset! Did you collect it yourself? I'd love to work in Panama flora sometime...

**Comment by dylancraven** [comment]
Hi Rachel - Yes, I collected this data - lots of fun (and sweat). Thanks
for setting up the dataset registration page, it's definitely helped
motivate me to contribute.

Best,

Dylan
