### ISSUE TITLE
A trait collection of marine fish species from North Atlantic and Northeast Pacific continental shelf seas

### ISSUE THREAD

**Issue by eshdb** [open-traits-network/open-traits-network.github.io#91]
Please fill out the template below and click "submit" to request a trait dataset to the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your submission.

```
---
layout: 
id: 
name: A trait collection of marine fish species from North Atlantic and Northeast Pacific continental shelf seas
datasetDOI_URL: https://doi.pangaea.de/10.1594/PANGAEA.900866
contactName: Esther Beukhof | Aurore Maureaud
contactEmail: esther.beukhof@wur.nl | auma@aqua.dtu.dk
license: CC BY 4.0
traitList: 
higherGeography: North Atlantic | North Pacific
decimalLatitude:
decimalLongitude:
taxon: Fish
eventDate: about 1980 to current
paperDOIcitation: 10.1594/PANGAEA.900866
description: A trait collection of marine fish species from North Atlantic and Northeast Pacific continental shelf seas.
taxaList: 6216 fish taxa, standardized based on World Register of Marine Species
usefulClasses: mostly species-, genus- and family level traits
dataStandard: Standardization of taxonomy based on http://marinespecies.org/
standardizationScripts: 
webpage: 
---
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_datasets#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hi @eshdb - 
Thanks for registering your fish trait dataset with opentraits network. Your registry entry is available at http://opentraits.org/datasets/beuker-2019 . 

Please let me know if you have any questions,
groetjes,
-jorrit
