### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by ibartomeus** [open-traits-network/open-traits-network.github.io#93]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: ibartomeus
name: Ignasi Bartomeus
email: nacho.bartomeus@gmail.com
homepage: http://www.bartomeuslab.com
lat: 37.400174
long: -5.997289
affiliation: Estación Biológica de Doñana (EBD-CSIC)
github: ibartomeus
---

Ignasi is a community ecologist based in Seville, Spain. 

## Collaboration statement
I am broadly interested in understanding how global change drivers impact community structure and composition, and how those impacts translate to the ecosystem functioning. I like to work with plant-pollinator communities because they show complex responses to land use change, climate warming or biological invasions, and encapsulate a critical ecosystem function, pollination.

I often work with bee traits and I am working in compiling an open database on bee traits.
```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by bmaitner** [comment]
Hi Ignasi,

I've added you to the members page and your profile is now visible on opentraits.org.  Note that I modified your username to 'i-bartomeus' to match the kebab case format of other usernames. 

Welcome aboard!
