### ISSUE TITLE
I'd like to join the Open Traits Network

### ISSUE THREAD

**Issue by diogoprov** [open-traits-network/open-traits-network.github.io#95]
Please update the template below and click "Submit" to let us know you'd like to become a member of the Open Traits Network. Please allow for some time for @open-traits-network/editors to review your request.

```
---
layout: member
id: diogo-b-provete
name: Diogo Borges Provete
email: diogo.provete@ufms.br
homepage: http://diogoprovete.weebly.com
lat: -20.499616
long: -54.611458
affiliation: Department of Ecology, Federal University of Mato Grosso do Sul, Campo Grande, MS, Brazil 
github: diogoprov
---

Diogo is an amphibian ecologist and evolutionary biologist in Campo Grande, Brazil. 

## Collaboration statement
I have engaged in trait- and phylogenetic-based approaches to community and evolutionary ecology since the begining of my PhD in 2011. I usually work on amphibians, but I have papers and advise students with other groups as well. My research programs combine traits and phylogenetic  comparative methods to understand ecological patterns at multiple spatial scales. I have a small trait data base on anuran larvae I worked durgin my master's, but I plan to contribute other datasets from my students. 

I can offer expertise in workflows for cleaning occurrence data and combining with trait data in R. I am also happy to help connect people together in Latin America around traits by running working groups, hosting visitors in my lab, organising symposia at conferences and maintaining our Open Traits website.


```

Editors @open-traits-network/editors: please see https://github.com/open-traits-network/open-traits-network.github.io/tree/master/_members#readme for information on registration process.

**Comment by jhpoelen** [comment]
Hi @diogoprov , welcome to the open traits network! You profile is available at http://opentraits.org/members/diogo-b-provete . If you'd like to make edits to your profile, please use the "edit" button on the profile. And . . . if you have any interest in maintaining https://opentraits.org - the more the merrier! There's much work to be done. 

-jorrit

**Comment by jhpoelen** [comment]
PS - small suggestion  -Please run a spell check on your profile. I noticed some minor typos. For example: "begining" should be "beginning" .
